//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SumerProject.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> ID_Size { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string Adress { get; set; }
    
        public virtual product product { get; set; }
        public virtual Sizes Sizes { get; set; }
        public virtual users users { get; set; }
    }
}
